# "$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
format = """\
$directory\
$git_branch$git_commit$git_state $git_status\
$character\n
"""

right_format = """
$singularity\
$kubernetes\
$vcsh\
$c\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$pulumi\
$purescript\
$python\
$raku\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$meson\
$spack\
$memory_usage\
$gcloud\
$openstack\
$azure\
$cpp\
$pixi\
$php\
$crystal\
$custom\
$status\
$time
"""

continuation_prompt = '▶▶ '

[directory]
disabled = false
format = "[$path](bold fg:#8be9fd)"
truncate_to_repo = false

[git_branch]
format = " [  $branch](fg:#9198a1)"

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[[( $all_status$ahead_behind )](fg:#769ff0)]($style)'
style = "bg:#394260"

[time]
disabled = false
format = '[[  $time ](fg:#a0a9cb )]($style)'
time_format = "%R"

[deno]
format = " [deno](italic) [ ](green bold)"
version_format = "${raw}"

[lua]
format = " [lua](italic) [⨀ ]($style)"
style = "bold bright-yellow"
version_format = "${raw}"

[nodejs]
detect_extensions = []
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
format = "[ ](bold bright-green)"
version_format = "${raw}"

[python]
format = "[[ ](${virtualenv}) ${version}]($style)"
style = "bold bright-yellow"
version_format = "${raw}"

[ruby]
format = " [rb](italic) [ ]($style)"
style = "bold red"
version_format = "${raw}"

[rust]
style = "bold bright-red"
format = " rs(italic)  ($style)"

[swift]
format = " [sw](italic) [ ]($style)"
style = "bold bright-red"
version_format = "${raw}"

[buf]
style = "bold bright-red"
format = " [buf](italic) [■ $buf_version]($style)"

[c]
style = "bold bright-cyan"
format = " [ℂ (-$name)]($style)"

[cpp]
style = "bold bright-cyan"
format = " [cpp](italic) [$symbol]($style)"
symbol = "C++"

[kotlin]
format = " [kotlin](italic) [K]($style)"
style = "bold bright-red"

[ocaml]
format = " [ocaml](italic) [O]($style)"
style = "bold bright-yellow"

[perl]
format = " [perl](italic) [P]($style)"
style = "bold bright-cyan"

[php]
format = " [php](italic) [P]($style)"
style = "bold bright-red"

[pixi]
format = " [pixi](italic) [pixi]($style)"
style = "bold bright-yellow"

[rlang]
format = " [rlang](italic) [R]($style)"
style = "bold bright-cyan"

[meson]
format = " [meson](italic) [meson]($style)"
style = "bold bright-red"

[conda]
style = "bold bright-red"
format = " conda [◯$environment]($style)"

[dart]
style = "bold bright-cyan"
format = " dart [ ]($style)"

[elixir]
style = "bold bright-yellow"
format = " exs [ OTP ]($style)"

[elm]
style = "bold bright-red"
format = " elm [◩ ]($style)"

[golang]
style = "bold bright-blue"
format = " go [∩ ]($style)"

[haskell]
style = "bold bright-yellow"
format = " hs [❯λ ]($style)"

[java]
style = "bold bright-red"
format = " java [ ]($style)"

[julia]
style = "bold bright-cyan"
format = " jl [◎ ]($style)"

[memory_usage]
style = "bold bright-cyan"
format = " mem [▪▫▪ ${ram}( ${swap})]($style)"

[nim]
style = "bold bright-yellow"
format = " nim [▴▲▴ ]($style)"

[nix_shell]
format = '[$symbol nix⎪$state⎪]($style) [$name](italic dimmed white)'
impure_msg = '[⌽](bold dimmed red)'
pure_msg = '[⌾](bold dimmed green)'
style = 'bold italic dimmed blue'
symbol = ' '
unknown_msg = '[◌](bold dimmed yellow)'

[spack]
style = "bold bright-yellow"
format = " spack [◇$environment]($style)"

[zig]
style = "bold bright-yellow"
format = " zig [ ]($style)"

[scala]
format = " scala [ ]($style)"

[singularity]
style = "bold bright-yellow"
format = " [singularity](italic) [singularity]($style)"

[kubernetes]
style = "bold bright-cyan"
format = " [kubernetes](italic) [ ]($style)"

[vcsh]
style = "bold bright-red"
format = " [vcsh](italic) [vcsh]($style)"

[cobol]
style = "bold bright-yellow"
format = " [cobol](italic) [cobol]($style)"

[daml]
style = "bold bright-cyan"
format = " [daml](italic) [daml]($style)"

[dotnet]
style = "bold bright-red"
format = " [dotnet](italic) [.NET ]($style)"

[erlang]
style = "bold bright-yellow"
format = " [erlang](italic) [ ]($style)"

[fennel]
style = "bold bright-cyan"
format = " [fennel](italic) [ ]($style)"

[haxe]
style = "bold bright-red"
format = " [haxe](italic) [ ]($style)"

[helm]
style = "bold bright-yellow"
format = " [helm](italic) [helm]($style)"

[opa]
style = "bold bright-cyan"
format = " [opa](italic) [opa]($style)"

[pulumi]
format = " [pulumi](italic) [pulumi]($style)"
style = "bold bright-red"

[purescript]
style = "bold bright-yellow"
format = " [purescript](italic) [ ]($style)"

[raku]
style = "bold bright-cyan"
format = " [raku](italic) [raku]($style)"

[red]
style = "bold bright-red"
format = " [red](italic) [red]($style)"

[solidity]
style = "bold bright-yellow"
format = " [solidity](italic) [ ]($style)"

[terraform]
style = "bold bright-cyan"
format = " [terraform](italic) [terraform]($style)"

[vlang]
format = " [vlang](italic) [vlang]($style)"
style = "bold bright-red"

[vagrant]
format = " [vagrant](italic) [vagrant]($style)"
style = "bold bright-yellow"

[gcloud]
format = " [gcloud](italic) [gcloud]($style)"
style = "bold bright-cyan"
disabled = true

[openstack]
format = " [openstack](italic) [openstack]($style)"
style = "bold bright-red"

[azure]
format = " [azure](italic) [ ]($style)"
style = "bold bright-yellow"

[crystal]
format = " [crystal](italic) [ ]($style)"
style = "bold bright-cyan"
